jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m venv venv && source venv/bin/activate
      - run: pip install -r requirements.txt
      - run: ./run_tests.sh          # workflow stops here if tests fail